dist: xenial
language: go
go:
  - "1.11.x"

os:
- linux
- osx
- windows

env:
  global:
    - electron_cache: $home/.cache/electron
    - electron_builder_cache: $home/.cache/electron-builder
    - build_dir: build
    - buildlib_dir: $build_dir/libskycoin
    - lib_dir: lib
    - build_ui_travis_dir: $home/.skycoin-ui-travis
    - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 60s
    - BUILD_BRANCH: '(master,\ develop,\ feature/parallel-travis-test)'
  jobs:
    - if: stage = test
    - TEST_SUIT=units
    - TEST_SUIT=integrations

osx_image: xcode8
services: xvfb

jobs:
  # Exclude tests for windows
  exclude:
  - os: windows
    env: TEST_SUIT=units
  - os: windows
    env: TEST_SUIT=integrations
  # Build stage jobs
  include:
#   - name: linux-wallet-build
#     stage: build
#     os: linux
#     if: branch =~ env(BUILD_BRANCH)
  - name: osx-wallet-build
    stage: build
    os: osx
    if: branch IN BUILD_BRANCH
#   - name: windows-wallet-build
#     stage: build
#     os: windows
#     env:
#     - GOX_OUTPUT='.gox_output'
#     if: branch =~ env(BUILD_BRANCH)

cache:
  directories:
  - electron/node_modules
  - electron/src/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds
  - src/gui/static/node_modules

addons:
  chrome: stable

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi

install:
  # Install gox
  - if [[ $TRAVIS_BUILD_STAGE_NAME == "test" ]]; then go get github.com/mitchellh/gox; fi
  # Install dependences for building wallet
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" == false ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils libudev-dev libusb-1.0-0-dev; fi
  - if [[ ! -d $GOPATH/src/github.com/SkycoinProject/skycoin ]]; then mkdir -p $GOPATH/src/github.com/SkycoinProject; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/SkycoinProject/skycoin; fi
  - cd $GOPATH/src/github.com/SkycoinProject/skycoin
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then nvm install 10.16.3 && nvm use 10.16.3; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./ci-scripts/install-nodejs-win.sh; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TRAVIS_BRANCH" =~ ^(master|develop|feature/parallel-travis-test)$ || -n "$TRAVIS_TAG" ]]; then ./ci-scripts/add-key.sh; fi
  # Source the ~/.bashrc to update the PATH for windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then source $HOME/.bashrc; fi

script:
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]] && [[ "$TRAVIS_BUILD_STAGE_NAME" == "test" ]]; then ./ci-scripts/lint-and-test.sh $TEST_SUIT; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" =~ ^(master|develop|feature/parallel-travis-test)$ || -n  "$TRAVIS_TAG" ]]; then ./ci-scripts/build-wallet.sh; fi

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  local_dir: electron/release
  upload_dir: wallet
  acl: public_read
  region: $AWS_REGION
  edge: true # opt in to dpl v2
  on:
    repo: SkycoinProject/skycoin
    tags: true

notifications:
  email:
    - travis@skycoin.com
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
